// c02ex02.cs

using System;

class Program
{
    static void Main(string[] args)
    {
        // Funções matemáticas
        Console.WriteLine(Math.Cos(1));   // Saída: 0.54030...
        Console.WriteLine(Math.Exp(1));   // Saída: 2.71828...
        Console.WriteLine(Math.Log(2));   // Saída: 0.69314...
        Console.WriteLine(Math.Sin(1));   // Saída: 0.84147...
        Console.WriteLine(Math.Sqrt(2));  // Saída: 1.41421...
    }
}
