' c02ex02.vb

Module Program
    Sub Main(args As String())
        ' Funções matemáticas
        Console.WriteLine(Math.Cos(1))   ' Saída: 0.54030...
        Console.WriteLine(Math.Exp(1))   ' Saída: 2.71828...
        Console.WriteLine(Math.Log(2))   ' Saída: 0.69314...
        Console.WriteLine(Math.Sin(1))   ' Saída: 0.84147...
        Console.WriteLine(Math.Sqrt(2))  ' Saída: 1.41421...
    End Sub
End Module
