! c07ex09.f95

PROGRAM c07ex09
  IMPLICIT NONE

  INTEGER :: LIMITE

  WRITE(*,'(A,$)') 'Qual fatorial: '
  READ(*,*) LIMITE

  WRITE(*,'(A,I0)') 'Fatorial = ', FATORIAL(LIMITE)

  WRITE(*,*)
  WRITE(*,'(A,$)') 'Tecle <Enter> para encerrar... '
  READ(*,*)

CONTAINS

  RECURSIVE FUNCTION FATORIAL_BASE(N, P) RESULT(RESULTADO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: N, P
    INTEGER :: RESULTADO

    IF (N == 0) THEN
      RESULTADO = P
    ELSE
      RESULTADO = FATORIAL_BASE(N - 1, N * P)
    END IF
  END FUNCTION FATORIAL_BASE

  FUNCTION FATORIAL(N) RESULT(RESULTADO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: N
    INTEGER :: RESULTADO

    RESULTADO = FATORIAL_BASE(N, 1)
  END FUNCTION FATORIAL

END PROGRAM c07ex09
